### ISSUE TITLE
Export types to be used with typescript

### ISSUE THREAD

**Issue by geshan** [passiv/snaptrade-node-sdk#1]
This is a pretty good SDK/package to call the snaptrade/passiv API.

As it is written in Typescript it would be even better to export the types so that they can be leveraged when working with typescript. Currently, only the compiled dist is being pulled in when installing this package from npm js. Or maybe I am missing something.

**Comment by ShayanAbedi** [comment]
Thanks for checking out the package @geshan! And that's a great feedback. I'll definitely add that to the package.

**Comment by geshan** [comment]
@ShayanAbedi are you planning to do it soon? :)

**Comment by ShayanAbedi** [comment]
sorry, just saw your comment now but thanks for opening a PR for it @geshan. also may I ask what partner you're with?
