### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by geshan** [passiv/snaptrade-node-sdk#7]
It would be best to keep the tags in sync with GitHub and NPM.

The last release is [1.0.9](https://www.npmjs.com/package/@snaptrade/js-fetch-api/v/1.0.9) and with the PRs being merged it would be best to use them and have patch/minor releases as per need.

Please release a new version with the new features added, thanks!

**Comment by brendanwood** [comment]
Thank you, good call! We will roll out the new version shortly.

**Comment by ShayanAbedi** [comment]
[1.1.0](https://www.npmjs.com/package/@snaptrade/js-fetch-api/v/1.1.0) is now released

**Comment by geshan** [comment]
@ShayanAbedi that version 1.1.0 unfortunately only has the types, not the new API changes.
