### ISSUE TITLE
Create a new release that includes the latest main

### ISSUE THREAD

**Issue by geshan** [passiv/snaptrade-node-sdk#9]
The current release 1.1.1 also doesn't have the latest changes. It would be great to keep the tags on GitHub and NPM sync. Currently, there is no way to track what changed between versions. 

I am not sure how, but the following PRs are not included in the `dist` of the NPM package:

* https://github.com/passiv/snaptrade-node-sdk/pull/4
* https://github.com/passiv/snaptrade-node-sdk/pull/5
* https://github.com/passiv/snaptrade-node-sdk/pull/8

When I do a `npm run build` on the main branch in my fork/the main GitHub repo those changes are there. Not sure why they are not coming into NPM.

Please have a look at this issue, it is a blocking one. It would be best to check what NPM has after each release too. Thanks!

**Comment by geshan** [comment]
To be sure, I deleted my `node_modules` and `yarn.lock` file and installed `1.1.1`, it didn't have the latest changes.

**Comment by ShayanAbedi** [comment]
so sorry about this @geshan. Apparently, I didn't do a build last time but I just released another version and confirmed that it has the latest changes in it. I'll make sure to add GitHub tags so it's clear what changed. Please let me know if it didn't work for you

**Comment by geshan** [comment]
@ShayanAbedi please include this PR too in the next release: https://github.com/passiv/snaptrade-node-sdk/pull/10 , thanks!

**Comment by ShayanAbedi** [comment]
done @geshan
